name: Deploy para Koyeb via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build e push da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/monolito-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/monolito-backend:latest

      - name: Deploy no Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/v1/services/${{ secrets.KOYEB_APP_NAME }}/deployments" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
