# @MonolitoBackend_Api_HostAddress = http://localhost:5288
@MonolitoBackend_Api_HostAddress = http://localhost:5001

GET {{MonolitoBackend_Api_HostAddress}}/api/categories
Accept: application/json
###

POST {{MonolitoBackend_Api_HostAddress}}/api/categories
Accept: application/json
Content-Type: application/json

{
    "name": "New Category",
    "description": "This is a new category"
}
###

POST {{MonolitoBackend_Api_HostAddress}}/api/users
Accept: application/json
Content-Type: application/json

{
    "name": "everton1",
    "password": "senha"
}
###

POST {{MonolitoBackend_Api_HostAddress}}/api/auth
Accept: application/json
Content-Type: application/json

{
    "name": "everton1",
    "password": "senha"
}
###

GET {{MonolitoBackend_Api_HostAddress}}/api/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTk2ODE4ZC02MmU1LTcyOTUtOWNjOS01ZGI5MjkxMDNkN2QiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZXZlcnRvbjEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzQ1OTQxMzYzLCJpc3MiOiJNb25vbGl0b0JhY2tlbmQiLCJhdWQiOiJNb25vbGl0b0Zyb250ZW5kIn0.zQIZDVY-nqign-OQNgaHJ0WLNqUgobIAHWAPJ5C2FAk
###
