services:
  postgres:
    image: postgres:latest
    container_name: postgres-monolito
    restart: always
    environment:
      POSTGRES_DB: MonolitoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: