version: "3.8"

services:
  postgres:
    image: postgres-monolito-backup
    container_name: postgres-monolitoDB-restore
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"  # Evita conflito com a instância original
    volumes: []
