version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monolito-api
    depends_on:
      - postgres
    ports:
      - "5001:8080"  # http://localhost:5001
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__PostgreSql: Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres

  postgres:
    image: postgres:latest
    container_name: postgres-monolitoDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      - ./postgres/backup:/backup

  frontend-usuarios:
    build:
      context: ./frontend-usuarios
      dockerfile: Dockerfile
    container_name: monolito-frontend
    ports:
      - "5002:80"
    depends_on:
      - api

  frontend-categorias:
    build:
      context: ./frontend-categorias
    container_name: frontend-categorias
    ports:
      - "5003:80"
    depends_on:
      - api
