services:
  postgres:
    image: postgres:latest
    container_name: postgres-monolitoDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # networks:
    #   - my_network

# /